[package]
name = "DocumentGenerator"
version = "0.1.0"
authors = ["Dinath <dinath22@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
